"""add items in stock to Offer

Revision ID: d44752bdb975
Revises: 157fd135a037
Create Date: 2022-05-19 13:23:52.134468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44752bdb975'
down_revision = '157fd135a037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('items_in_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'items_in_stock')
    # ### end Alembic commands ###
