version: "3"
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - BASE_URL_OFFERS=https://applifting-python-excercise-ms.herokuapp.com/api/v1